apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-ruler-falco-io
  namespace: loki
  labels:
    ruler.loki.grafana.com/rule: "true"  # <- muito importante
data:
  alerts.yaml: |
    groups:
    - name: pvc-io
      interval: 30s
      rules:
      - alert: PVC_IO_Spike_1x
        expr: |
          sum by (k8s_ns_name,k8s_pod_name,persistentvolumeclaim) (
            count_over_time({rule="Storage open-for-write", source="synthetic",
              k8s_ns_name=~".+", k8s_pod_name=~".+", persistentvolumeclaim=~".+"}[15m])
          ) >= 1
        for: 0m
        labels:
          severity: warning
        annotations:
          summary: "PVC {{ $labels.persistentvolumeclaim }} com escrita detetada"
          description: "Pod {{ $labels.k8s_ns_name }}/{{ $labels.k8s_pod_name }} escreveu no PVC {{ $labels.persistentvolumeclaim }} (>=1x/15m)."

      - alert: PVC_IO_Spike_3x
        expr: |
          sum by (k8s_ns_name,k8s_pod_name,persistentvolumeclaim) (
            count_over_time({rule="Storage open-for-write", source="synthetic",
              k8s_ns_name=~".+", k8s_pod_name=~".+", persistentvolumeclaim=~".+"}[15m])
          ) >= 3
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: "PVC {{ $labels.persistentvolumeclaim }} com alta taxa de IO"
          description: "Pod {{ $labels.k8s_ns_name }}/{{ $labels.k8s_pod_name }} excedeu 3 aberturas em 15m no PVC {{ $labels.persistentvolumeclaim }}."
          
