watchRules: true

service:
  type: ClusterIP
  port: 2803

rbac:
  create: true

config:
  rulesOverride: |
    - action: Label Suspicious
      actionner: kubernetes:label
      parameters:
        level: pod
        labels: { suspicious: "true" }

    - action: Terminate Pod
      actionner: kubernetes:terminate
      parameters:
        grace_period_seconds: 5
        ignore_statefulsets: true
        ignore_daemonsets: true

    - rule: PVC IO spike (label)
      match: { source: prometheus, rules: [PVC_IO_Spike_1x] }
      actions: [ { action: Label Suspicious } ]

    - rule: PVC IO spike (kill)
      match: { source: prometheus, rules: [PVC_IO_Spike_3x] }
      actions: [ { action: Terminate Pod } ]

replicaCount: 2
logLevel: debug
