name: markdown
on: [push, pull_request]
jobs:
  mdl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Markdownlint
        uses: avto-dev/markdown-lint@v1
        with:
          config: .markdownlint.json
          args: '**/*.md'
