name: validate
on: [push, pull_request]
jobs:
  kubeconform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker://ghcr.io/yannh/kubeconform:latest
        with:
          args: -strict -summary -ignore-missing-schemas manifests/**/*.yaml
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ibiqlik/action-yamllint@v3
