# .github/workflows/validate.yaml
name: validate
on: [push, pull_request]

jobs:
  kubeconform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: kubeconform
        uses: docker://ghcr.io/yannh/kubeconform:latest
        with:
          args: >-
            -strict -summary
            -kubernetes-version 1.28.0
            -schema-location default
            -ignore-missing-schemas
            manifests

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup yamllint
        run: pipx install yamllint
      - name: Lint manifests
        run: yamllint -c .yamllint manifests
      - name: Lint helm-values
        run: yamllint -c .yamllint helm-values
      - name: Lint workflows
        run: yamllint -c .yamllint .github/workflows



